apiVersion: v1
kind: Service
metadata:
  name: mycafe-service
spec:
  type: NodePort
  selector:
    app: my-cafe-example
    release: my-cafe-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
