apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cafe
  labels:
    app: my-cafe-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-cafe-example
  template:
    metadata:
      labels:
        app: my-cafe-example
    spec:
      containers:
        - name: mycafe-deployment
          image: jinchoel/mycafe
          ports:
            - containerPort: 3000
